name: Build and Deploy

on:
  push:
    branches:
      - main  # 배포를 원하는 브랜치

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'  # 사용 중인 JDK 버전

      - name: Build the project
        run: ./mvnw clean package  # Maven 사용 시, Gradle 사용 시 ./gradlew build

      - name: Deploy to GCP via SFTP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_HOST }}  # GCP 서버 IP 또는 도메인
          username: ${{ secrets.GCP_USERNAME }}  # SFTP 사용자 이름
          key: ${{ secrets.GCP_PRIVATE_KEY }}  # SFTP 개인 키
          port: 22
          source: "target/*.jar"  # 빌드된 JAR 파일의 경로
          target: "/home/rodzld18/"  # GCP 서버에 JAR 파일을 배포할 경로

      - name: Execute JAR on GCP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_HOST }}  # GCP 서버 IP 또는 도메인
          username: ${{ secrets.GCP_USERNAME }}  # SFTP 사용자 이름
          key: ${{ secrets.GCP_PRIVATE_KEY }}  # SFTP 개인 키
          port: 22
          script: |
            cd /home/rodzld18/  # JAR 파일이 위치한 디렉토리로 이동
            nohup java -Duser.timezone=Asia/Seoul -jar your-application.jar > output.log 2>&1 &
            # output.log: 로그 파일, 출력 및 에러를 모두 기록합니다.
